version: '3.8'

services:
  ffc-sfi-calculator:
    build:
      context: .
      target: production
    image: ffc-sfi-calculator
    container_name: ffc-sfi-calculator
    environment:
      AGREEMENT_CHANGED_TOPIC_ADDRESS: ${AGREEMENT_CHANGED_TOPIC_ADDRESS:-notset
      AGREEMENT_CALCULATOR_SUBSCRIPTION_ADDRESS: ${AGREEMENT_CALCULATOR_SUBSCRIPTION_ADDRESS:-notset}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      UPDATE_AGREEMENT_QUEUE_ADDRESS: ${UPDATE_AGREEMENT_QUEUE_ADDRESS:-notset}
