environment: development
name: ffc-sfi-calculator
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-calculator

labels: {}

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: ffc-sfi-calculator-config-map

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0
  redeployOnChange: update this field to force a change
  runAsNonRoot: true
  runAsUser: 1000

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 120Mi
  limitCpu: 120m
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  port: 3000
  messageQueueHost: dummy
  updateAgreementQueueAddress: update-agreement
  agreementChangedTopicAddress: agreement-changed
  agreementChangedSubscriptionAddress: agreement-changed

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
